### ISSUE TITLE
Add RSS feed?

### ISSUE THREAD

**Issue by Pat-Lafon** [BD103/bd103.github.io#4]
Hello, Great blog post!

It doesn't seem like you have an rss feed so that people can subscribe to your blog. Is this something you would consider adding?

**Comment by BD103** [comment]
Hey, thanks for the suggestion! I’ll look into adding one :)

**Comment by BD103** [comment]
Hello! I have added RSS and Atom feeds with ef2423e04646e449c8ec3f1a421b692d8fb8fb75. I don't use a news aggregator though, so I have not tested this thoroughly.

If you experience any issues, feel free to open a new issue / respond to this one!

**Comment by Pat-Lafon** [comment]
Works for me, thanks!
